# Generated by Django 6.0.2 on 2026-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrez_gene_id', models.BigIntegerField(db_index=True, unique=True)),
                ('mim_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('symbol', models.CharField(max_length=50)),
                ('approved_name', models.CharField(max_length=255)),
            ],
        ),
    ]
